apiVersion: v1
kind: Service 
metadata:
  name: back-end
spec: 
  type: ClusterIP
  ports:
    - targetport: 80
      port: 80
      nodeport: 30008 
  selector:
    app: posh1
    type: back-end

    #kubectl create -f service-definition.yml
    # kubectl get services
    #curl http://192.168.1.2:30008 (Ip of Node)
