apiVersion: apps/v1
kind: Deployment
metadata:
  name: posh-deployment
  labels:
    app: posh-app
    type: front-end

spec:
  template:
    metadata:
      name: posh-pod
      labels:
        app: posh-app
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
