apiVersion: v1
kind: Pod 
metadata:
  namespace: dev
  name: posh1-pod
  labels:
    app: posh1
    type: front-end
spec: 
  containers:
    - name: nginx-container
      image: nginx
  nodeName: Name of node
  tolerations:
    - key: app 
      operator: Equals 
      value: blue
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: size
              operators: In
              values: 
              - Large
              - Medium 



#kubectl create -f pod-definition.yml
#kubectl get pods
#kubectl describe pod posh1-pod

#kubectl create -f pod-definition.yml --namespace=dev