apiVersion: v1
kind: Service 
metadata:
  name: posh1-service
spec: 
  type: NodePort
  ports:
    - targetport: 80
      port: 80
      nodeport: 30008 
  selector:
    app: posh1
    type: front-end

    #kubectl create -f service-definition.yml
    #curl http://192.168.1.2:30008 (Ip of Node)
